### ISSUE TITLE
 功能建议

### ISSUE THREAD

**Issue by itMcdull** [YYFlutter/flutter-custom-dialog#1]
我希望在我在操作一些设置的时候,弹出dialog,提示本次设置的成功或失败, 需要3s之后自动消失dialog

**Comment by wanwusangzhi** [comment]
toast会考虑

**Comment by AndroidHensen** [comment]
先用定时器  手动 调用dimiss方法，后续会考虑加上

**Comment by AndroidHensen** [comment]
toast可以通过现在的弹窗自定义去封装，定时器暂时不实现，太过于业务化
