### ISSUE TITLE
install ios device  arm64 error

### ISSUE THREAD

**Issue by ZeroMoment** [YYFlutter/flutter-custom-dialog#22]
xcode run is success.

but androidstudio run to ios device. error:

Non-fat binary /Users/lizhiming/dev_space/work_space/flutter_project/RedPaperClient/build/ios/Debug-iphoneos/Runner.app/Frameworks/flutter_custom_dialog.framework/flutter_custom_dialog is not armv7. Running lipo -info:
    Non-fat file: /Users/lizhiming/dev_space/work_space/flutter_project/RedPaperClient/build/ios/Debug-iphoneos/Runner.app/Frameworks/flutter_custom_dialog.framework/flutter_custom_dialog is architecture: arm64
    Command PhaseScriptExecution failed with a nonzero exit code

**Comment by AndroidHensen** [comment]
It could be a problem with AndroidStudio support
