### ISSUE TITLE
在使用listViewOfRadioButton时能否有一个默认的选择项？否则每次打开都选择第一个

### ISSUE THREAD

**Issue by LeiQiao** [YYFlutter/flutter-custom-dialog#29]
在使用listViewOfRadioButton时能否有一个默认的选择项？
在下面的代码里面

radioDialog(context, String title, List<String> buttons, {okTitle='确定', cancelTitle='取消', currentSelectedIndex=-1, IndexCallback onTap}) {
  List<RadioItem> radioItems = List.generate(buttons.length, (index) {
    return RadioItem(
      padding: EdgeInsets.only(left: 6.0),
      text: buttons[index],
      color: Colors.black,
      fontSize: 16.0,
    );
  });
  int selectedIndex = 0;

  return YYDialog().build(context)
    ..width = 280
    ..borderRadius = 4.0
    ..text(
      padding: EdgeInsets.fromLTRB(18.0, 22.0, 18.0, 18.0),
      text: title,
      color: Colors.black,
      fontSize: 18.0,
      fontWeight: FontWeight.w500,
    )
    ..divider()
    ..listViewOfRadioButton(
        **// 希望可以在这里加一个当前选中的某一项currentSelectedIndex，否则每次打开都是选择第一个**
        items: radioItems,
        height: 370,
        activeColor: Colors.blue,
        onClickItemListener: (index) {
          selectedIndex = index;
        })
    ..divider()
    ..doubleButton(
      padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
      gravity: Gravity.right,
      text1: cancelTitle,
      color1: Colors.blue,
      fontSize1: 14.0,
      fontWeight1: FontWeight.bold,
      text2: okTitle,
      color2: Colors.blue,
      fontSize2: 14.0,
      fontWeight2: FontWeight.bold,
      onTap2: () {
          if (onTap != null) Future.delayed(Duration.zero, () {
            onTap(selectedIndex);
          });
      }
    )
    ..show();
}

**Comment by AndroidHensen** [comment]
support in v1.0.17
