### ISSUE TITLE
dialog 打开后如何动态刷新内容

### ISSUE THREAD

**Issue by mulieli** [YYFlutter/flutter-custom-dialog#33]
dialog 展示后 修改状态改变dialog内的内容  现在好像不行

**Comment by 0131LWG** [comment]
请一下有答案了吗？我也是一样使用setState更新不生效

**Comment by mulieli** [comment]
> 请一下有答案了吗？我也是一样使用setState更新不生效

动态刷新 我是自己写的弹窗
这个好像现在没什么回复

**Comment by AndroidHensen** [comment]
参考项目中example中的ListRatio这个封装，其中的思路是把你需要更新的UI包装成Stateful的就可以改变了。这个不行吗？？
