### ISSUE TITLE
连续打开关闭多次后 导致diaolog 关不掉

### ISSUE THREAD

**Issue by mulieli** [YYFlutter/flutter-custom-dialog#34]
添加了一个加载框   多次调用后 导致dialog 关不掉   并且 isShowing 是false

**Comment by AndroidHensen** [comment]
贴一下完整代码

**Comment by mulieli** [comment]
> 贴一下完整代码
<img width="848" alt="WeChat68fc481cbff1861af11dfab14b519d14" src="https://user-images.githubusercontent.com/24307960/78341525-71b8c700-75ca-11ea-98d0-4c0a68dea3d0.png">
<img width="596" alt="WeChat1d5edfbf049498c2f9c71510b0971cbd" src="https://user-images.githubusercontent.com/24307960/78341549-7da48900-75ca-11ea-8c80-ee579f54c842.png">

**Comment by simanlx** [comment]
经过反复测试 是显示diaolog 需要时间   在Dialog.dismiss(); 的时候 显示还没完成  isShowing 还是false
