### ISSUE TITLE
dismiss dialog when user press button inside it

### ISSUE THREAD

**Issue by brizaldi** [YYFlutter/flutter-custom-dialog#37]
so i have this dialog with 2 button inside : CANCEL and DISCARD

![Annotation 2020-04-26 142102](https://user-images.githubusercontent.com/41714881/80300703-2d83a580-87c9-11ea-81f4-beaa54437fdd.png)

my question is, how can i dismiss the dialog when user press one of those button? should i use Navigator.pop ?

**Comment by AndroidHensen** [comment]
var yyDialog = YYDialog();
yyDialog?.dismiss();

**Comment by dhalloop7** [comment]
I tried the same but not working.

**Comment by AndroidHensen** [comment]
1. make sure your context is scaffold. 
2. you can clone my code,run my project,i have a example.

**Comment by brizaldi** [comment]
@dhalloop7 instead of using dismiss, try this:

`Navigator.of(context, rootNavigator: true).pop();`

dont forget to pass context from the your root widget

**Comment by dhalloop7** [comment]
I tried all above solutions but still it's not dismiss the dialog. Even I am getting callback as well but it's not dismissing the dialog and If I try to dismiss dialog inside callback sometime it's close the current page

**Comment by AndroidHensen** [comment]
try v1.0.20   'useRootNavigator'  property
