### ISSUE TITLE
flutter打印出log

### ISSUE THREAD

**Issue by iperfectapp** [YYFlutter/flutter-custom-dialog#4]
![image](https://user-images.githubusercontent.com/3021764/66658541-45a03700-ec74-11e9-856e-64f4011a9072.png)

**Comment by iperfectapp** [comment]
请问是什么意思呢？

**Comment by AndroidHensen** [comment]
表示你的弹窗已经显示出来了，可以忽略，后续会删除

**Comment by AndroidHensen** [comment]
在 v1.0.10 已经改正日志
