### ISSUE TITLE
listViewOfListTile to be scrollable

### ISSUE THREAD

**Issue by daniel-v** [YYFlutter/flutter-custom-dialog#41]
I have the followin use-case:

I have a dialog that I'd like to use to display some options to the user. The number of list items that I'd like to show is more than what can be displayed on a single screen, therefore some scrolling would be nice inside the dialog.

Can we figure out a way to do that with your built in `listViewOfListTile` function? Things I'm considering now:

1. just not use `listViewOfListTile` but that is so meh... I would need to rewrite much of what you already have written
2. add an optional argument to the method `scrollable`. Setting it to `true` would encapsulate the ListView in a `SingleChildScrollView`. 
3. maybe add a `Widget decoratorWidget` argument to the method that would allow encapsulating the entire list in anything, in my case a `SingleChildScrollView`

And of course, I'm open to any suggestions how one would go about doing that.

**Comment by AndroidHensen** [comment]
You can use the `widget()` method to customize the dialog you want, and the listViewOfListTile here is just a Demo
