### ISSUE TITLE
YYDialog.init(context);  报错

### ISSUE THREAD

**Issue by addappcn** [YYFlutter/flutter-custom-dialog#43]
//init common dialog
  YYDialog.init(context); 具体去掉用的时候不传context 会报错。每个使用地方传context  不会报错。

error info：
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.

**Comment by taozhipeng1990** [comment]
大佬好像不更新了。好像不玩flutter的样子

**Comment by addappcn** [comment]
是吗  ？
