### ISSUE TITLE
Android Studio打包出现错误，请问怎么解决啊？

### ISSUE THREAD

**Issue by iperfectapp** [YYFlutter/flutter-custom-dialog#5]
ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_custom_dialog' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0
Update plugins

**Comment by AndroidHensen** [comment]
support v1.0.11
