### ISSUE TITLE
Add Gravity.spaceEvenly to double Button Property!

### ISSUE THREAD

**Issue by JAECHON-YU** [YYFlutter/flutter-custom-dialog#51]
For the Dialog with wider width, double Button with center gravity look awkward.

What about to add space evenly alignment to double Button?

Do we have any side effects which can cause problem with other function using Gravity?

Thanks for your Nice Package

![KakaoTalk_Photo_2021-01-18-06-54-49](https://user-images.githubusercontent.com/42856326/104857201-22c1ff80-595a-11eb-8268-fb68d0873fda.jpeg)

![KakaoTalk_Photo_2021-01-18-06-45-53](https://user-images.githubusercontent.com/42856326/104857106-9dd6e600-5959-11eb-88d2-adbeb9427552.jpeg)

**Comment by AndroidHensen** [comment]
1.0.21
