### ISSUE TITLE
 version: v1.2.0 , when upgrade flutter sdk to v3.3.0,  Remove deprecated FlatButton 

### ISSUE THREAD

**Issue by SeaZhang** [YYFlutter/flutter-custom-dialog#67]
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_custom_dialog-1.2.0/lib/flutter_custom_dialog.dart:120:13: Error: The method 'FlatButton' isn't defined for the class
'YYDialog'.
[        ]  - 'YYDialog' is from 'package:flutter_custom_dialog/flutter_custom_dialog.dart'

**Comment by AndroidHensen** [comment]
v1.3.0 done
