### ISSUE TITLE
为什么Widget里面不能放GridView，Expanded 等就弹不出来

### ISSUE THREAD

**Issue by mx4g** [YYFlutter/flutter-custom-dialog#7]

**Comment by AndroidHensen** [comment]
贴上代码给我，我测试下

**Comment by mx4g** [comment]
> 贴上代码给我，我测试下

///内容对话框
 YYDialog contentDialog(Widget widget,{width,height, gravity}) {
  return YYDialog().build()
    ..width = width
    ..gravity = gravity
    ..gravityAnimationEnable = true
    ..borderRadius = 4.0
    ..height = height
    ..widget(
       Container(
         child: 
         Column(
           children: <Widget>[
             Wrap(
               children: <Widget>[
                 Text("1.就这个可以，我现在用这个！！！"),
                 Text("2.就这个可以，我现在用这个！！！"),
                  Text("3.注释的代码3种情况都不行")
               ],
             )
           ],
         )
         //1.直接Listview不行
          // ListView(
          //     children: <Widget>[
          //       Text("11111"),
          //       Text("22222"),
          //       Text("33333")
          //     ],
          //   )

        //2.直接Column是可以的，但是嵌套Expanded也不行
        //  Column(
        //    children: <Widget>[
        //      Expanded(
        //        flex: 1,
        //        child: Text("Expanded1"),
        //      ),
        //      Expanded(
        //        flex: 2,
        //        child: Text("Expanded2"),
        //      )
        //    ],
        //  ),
         
         //3.直接GridView,不行
        // GridView.count(
        //   crossAxisCount: 2,
        //   childAspectRatio: 1.0,
        //   crossAxisSpacing: 10,
        //   mainAxisSpacing: 10,
        //   children: <Widget>[
        //     Text("1111"),
        //     Text("2222"),
        //     Text("3333")
        //   ],
        // )
       )
    )
    ..show();
}

**Comment by mx4g** [comment]
> > 贴上代码给我，我测试下
> 
> ///内容对话框
> YYDialog contentDialog(Widget widget,{width,height, gravity}) {
> return YYDialog().build()
> ..width = width
> ..gravity = gravity
> ..gravityAnimationEnable = true
> ..borderRadius = 4.0
> ..height = height
> ..widget(
> Container(
> child:
> Column(
> children: [
> Wrap(
> children: [
> Text("1.就这个可以，我现在用这个！！！"),
> Text("2.就这个可以，我现在用这个！！！"),
> Text("3.注释的代码3种情况都不行")
> ],
> )
> ],
> )
> //1.直接Listview不行
> // ListView(
> // children: [
> // Text("11111"),
> // Text("22222"),
> // Text("33333")
> // ],
> // )
> 
> ```
>     //2.直接Column是可以的，但是嵌套Expanded也不行
>     //  Column(
>     //    children: <Widget>[
>     //      Expanded(
>     //        flex: 1,
>     //        child: Text("Expanded1"),
>     //      ),
>     //      Expanded(
>     //        flex: 2,
>     //        child: Text("Expanded2"),
>     //      )
>     //    ],
>     //  ),
>      
>      //3.直接GridView,不行
>     // GridView.count(
>     //   crossAxisCount: 2,
>     //   childAspectRatio: 1.0,
>     //   crossAxisSpacing: 10,
>     //   mainAxisSpacing: 10,
>     //   children: <Widget>[
>     //     Text("1111"),
>     //     Text("2222"),
>     //     Text("3333")
>     //   ],
>     // )
>    )
> )
> ..show();
> ```
> 
> }

整段代码直接复制就行，可以运行的，粘上来有些丑

**Comment by AndroidHensen** [comment]
你的子控件没有填大小，所以出不来，填上宽高就行了，外面嵌套一层可以增加宽高的

**Comment by mx4g** [comment]
> 你的子控件没有填大小，所以出不来，填上宽高就行了，外面嵌套一层可以增加宽高的

回复：可以，谢谢o(*￣︶￣*)o
