### ISSUE TITLE
确定 取消的时候 

### ISSUE THREAD

**Issue by kindao1** [YYFlutter/flutter-custom-dialog#8]
带有选择取消确定的时候，能根据输入的内容来判断对话框是否关闭吗？
比如我加了文本框，我要判断输入的文本框内容是否正确，如果内容不正确点击确定，对话框不关闭

**Comment by AndroidHensen** [comment]
把yydialog作为成员变量，(var dialog = YYDialog();)条件满足后， 调用api的dismiss方法即可
